#define C_DEFAULT "\e[39m"
#define C_BLACK "\e[30m"
#define C_RED  "\e[31m"
#define C_GREEN "\e[32m"
#define C_YELLOW "\e[33m"
#define C_BLUE "\e[34m"
#define C_MAGENTA "\e[35m"
#define C_CYAN "\e[36m"
#define C_GRAY "\e[37m"
#define C_WHITE "\e[97m"


#define BG_C_DEFAULT "\e[49m"
#define BG_C_BLACK "\e[40m"
#define BG_C_RED  "\e[41m"
#define BG_C_GREEN "\e[42m"
#define BG_C_YELLOW "\e[43m"
#define BG_C_BLUE "\e[44m"
#define BG_C_MAGENTA "\e[45m"
#define BG_C_CYAN "\e[46m"
#define BG_C_GRAY "\e[100m"
#define BG_C_WHITE "\e[107m"

